tarantool/multivac

- .flake8
- .github/workflows/test-last-seen.yml
- multivac/last_seen.py
Resulting CSV looks like this:
```csv
timestamp,test,conf,branch,status,count,runs_on,url,job_json,job_log,run_json
2022-06-22 16:23:18+00:00,app-luatest/gh_5747_crash_multiple_args_test.l>,,master,transient fail,38,graviton,https://github.com/tarantool/tarantool/runs/7008228471?check_suite_focus=true,https://multivac.hb.bizmrg.com/tarantool/tarantool/workflow_run_jobs/7008228471.json,https://multivac.hb.bizmrg.com/tarantool/tarantool/workflow_run_jobs/7008228471.log,https://multivac.hb.bizmrg.com/tarantool/tarantool/workflow_runs/2543635332.json
2022-06-22 16:14:02+00:00,replication/box_set_replication_stress.test.lua,vinyl,master,fail,20,macos-10.15,https://github.com/tarantool/tarantool/runs/7008230119?check_suite_focus=true,https://multivac.hb.bizmrg.com/tarantool/tarantool/workflow_ru …
```
> last_seen: provide links to stored json and log data

- README.md
- docs/gather_job_data/_includes/workflows.csv
- docs/gather_job_data/_includes/workflows.json
- multivac/gather_job_data.py
This patch extends parameters gathering with `gather_job_data.py`:
added branch name (from run data, `head_branch`) and commit hash
(from job data, `head_sha`).
Resolves #35
> gather_job_data: add branch and commit to data

- docs/gather_job_data/_includes/testrun_address_already_in_use.log
- multivac/docs.py
- multivac/gather_job_data.py
- multivac/sensors/failures.py
Detect specific failure reasons first. If none found in the whole log,
look for generic. This way, specific reasons aren't overshadowed by
generic ones, when those are found first in the logs.
Introduce one specific reason: "Address already in use", subject of
https://github.com/tarantool/test-run/issues/141
| test name                      | before | after |
|--------------------------------|--------|-------|
| total                          | 47     | 47    |
| testrun_address_already_in_use | 0      | 19    |
| testrun_test_failed            | 11     | 4     |
| dpkg_buildpackage_error        | 9      | 0     |
| unknown                        | 8      | 8     |
| integration_vshard_test_failed | 4      | 3     |
| testrun_test_hung 3            | 3      | 3     |
| dir_not_empty 3 …
> gather_job_data: detect specific before generic

- .env-example
- .gitignore
- README.md
- docs/gather_job_data.rst
- docs/index.rst
- docs/influxdb.rst
- docs/toctree.rst
- multivac/gather_job_data.py
- multivac/influxdb.py
- requirements.txt
This patch improves `multivac/gather_job_data.py` to store gathered
job data in InfluxDB. Credentials for connection must be set as
environment variables.
We use job id as uniq record identificator (`measurement`). The
following data set as tags:
* job name
* branch
* commit_sha
* runner platform
* runner label
* runner version
* runner name
* failure type
* status
The following data set as fields:
* time the job started at
* time the job completed at
Time the job queued at is taken as time for InfluxDB recording (Unix
time, nanoseconds)
Learn more in `docs/influxdb.rst`
Resolves #23
> influxdb: add the connector

- docs/influxdb.rst
- multivac/gather_job_data.py
In this patch we set failure reason as measurement and time job was in
queue and time job was in progress as fields. All the other data set as
tags.
> gather_job_data: change influxdb structure

- multivac/gather_job_data.py
Instead of fields 'time_job_in_queue' and 'time_job_in_progress' we
input just one field with value 1 to build time-based and total count
charts to see total amount variations by week for all failure types in
Grafana.
Added this option to GitHub CI for regular data collecting.
Part of https://github.com/tarantool/multivac/issues/39
> gather_job_data: improve influxdb data structure

- multivac/gather_test_data.py
This patch allows to store test records with no configuration with tag 'configuration' (before it was without this tag)
Part of #56
> gather_test_data: store `null` configuration

- multivac/gather_data.py
This patch adds a `branch` to test data structure for InfluxDB and fixes a typo in variable when detecting test subtype
> gather_data: add `branch`, fix variable typo

- .github/workflows/main.yml
- multivac/gather_data.py
This patch creates new data structure for new InfluxDB bucket to create
table view panel in Grafana: store links to commit, GH Action run job
page, run job log file, run job JSON file, workflow run JSON file.
Resolves https://github.com/tarantool/multivac/issues/2
> gather data: new bucket to create table

- .github/actions/write_to_db/action.yml
- .github/workflows/aws-sync.yml
- .github/workflows/buckets-create.yml
- .github/workflows/buckets-delete.yml
- .github/workflows/buckets-update.yml
- .github/workflows/main.yml
This patch adds three new workflows to create and fill, update (clear and re-fill) and delete buckets. Allows to test new data structure in Grafana without deployng to production and automates deploy new data structure to production.
Resolves #54
> ci: make test deploy to InfluxDB

- .github/actions/write_to_db/action.yml
- .github/workflows/buckets-create.yml
- .github/workflows/main.yml
- .gitignore
- multivac/gather_data.py
[gather_data: fix os_version collection for table bucket](https://github.com/tarantool/multivac/pull/76/commits/2d86ca4d0341c929f795c42a833519c8084c321f)
Store os version, not runner label
[gitignore: added venv to gitignore](https://github.com/tarantool/multivac/pull/76/commits/8b4432ea68af6d0a71212a10bcd660f5d707c0af)
[ci: fix branch update for test deploy](https://github.com/tarantool/multivac/pull/76/commits/06c8f31c783cb5793ddf8a5960eb65c36ba6e666)
Branch update was incorrect, this patch fixes it
PR tests:
> gather_data: fix os_version collection for table bucket

- .github/workflows/buckets-update.yml
- .github/workflows/testing.yml
- multivac/gather_data.py
This patch fixes tagging:
* For freebsd - added matcher to get correct runner version
* For all the jobs - if there are no data for any tag, store 'None'
This will help to show correct data on filtered Grafana
> gather_data: fix tagging for jobs

- .github/workflows/aws-sync.yml
- backup.sh
Fix problem with aws-sync: https://github.com/tarantool/multivac/actions/runs/3372709498
```
Run ./backup.sh workflow_runs
./backup.sh workflow_runs
shell: /usr/bin/bash -e {0}
+ [ 4 -eq 0 ]
+ DIR=o
+ /usr/local/bin/aws s3 sync /mnt/storage/multivac/o s3://multivac/tarantool/tarantool/o --endpoint-url http://hb.bizmrg.com/ --acl public-read
The user-provided path /mnt/storage/multivac/o does not exist.
Error: Process completed with exit code 255.
```
> ci: fix aws-sync.yml

- multivac/gather_data.py
- multivac/sensors/test_status.py
This patch adds compiler version from logs and glibc version from
static dict GLIBC_MAPER to JSON and to the InfluxDB tests bucket.
Resolves https://github.com/tarantool/multivac/issues/84
> gather_data: add compiler version

- .github/workflows/aws-sync.yml
- .github/workflows/main.yml
- .gitignore
- README.md
- multivac/fetch.py
- multivac/gather_data.py
- multivac/get_artifacts.py
- multivac/last_seen.py
Download artifacts, save them to S3 bucket
Store data in the path '\<owner\>/\<repo\>/workflow_runs' and '\<owner\>/\<repo\>/workflow_run_jobs' to work with several repositories.
Store data from both tarantool/tarantool and tarantool/tarantool-ee
repositories to S3 bucket.
Resolves https://github.com/tarantool/multivac/issues/97
Resolves https://github.com/tarantool/multivac/issues/94
> multivac: store each repo data in separate dirs

- multivac/gather_data.py
- multivac/get_artifacts.py
Before this patch, `gather_data` failed when there was an OS version
not in the LIBC_VERSIONS dict. This patch fixes it. Also in this patch
added libc version (musl) for alpine_3_16
> gather_data: fix LIBC detection

- multivac/gather_data.py
This patch adds tags 'compiler_version' and 'libc_version' to the table with data about failed tests to enable filter in Grafana
> gather_data: add compiler and libc tags to table

- multivac/fetch.py
There are some errors if the run log is empty:
```
Traceback (most recent call last):
File "./multivac/fetch.py", line 410, in <module>
job.download_log()
File "./multivac/fetch.py", line 234, in download_log
r = http_get(url)
File "./multivac/fetch.py", line 53, in wrapper
return http_get_function(*args, **kwargs)
File "./multivac/fetch.py", line 94, in http_get
content_type = r.headers['content-type']
File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
return self._store[key.lower()][1]
KeyError: 'content-type'
```
So for now we need to change the method to get header value, so the script won't fail. Need further work to find why the logs are empty.
Related to https://github.com/tarantool/multivac/issues/113
> fetch.py: don't fall with error if no content-type

- .github/workflows/buckets-delete.yml
- multivac/gather_data.py
gather_data: don't fail if there are no log
If there are failed job with no log file, the `gather_data` script
fails:
```
Traceback (most recent call last):
File "./multivac/gather_data.py", line 595, in <module>
result.gather_data()
File "./multivac/gather_data.py", line 309, in gather_data
job_failure_type, failure_line = detect_error(logs,
File "./multivac/gather_data.py", line 92, in detect_error
for number, line in enumerate(reverse_readline(logs)):
File "./multivac/gather_data.py", line 57, in reverse_readline
with open(filename, encoding='utf8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'tarantool/tarantool/workflow_run_jobs/11814288555.log'
```
This patch fixes this problem.
__________________________________________
ci: fix buckets-delete on step delete-env …
> ci, gather_data: minor improvements, bug fixes

- .github/workflows/main.yml
After 2.11.0-rc1, tarantool/tarantool branch 1.10 became deprecated, stable branches are master, 2.10, 2.11.
> ci: change stable branches

- .github/workflows/buckets-delete.yml
With the version dawidd6/action-download-artifact@v2.26.0, we had the
fail:
```
Error: no matching workflow run found with any artifacts?
```
This patch fixes this problem with using action version 2.25.0.
> ci: use dawidd6/action-download-artifact@v2.25.0 

- multivac/gather_data.py
This patch adds the link to the artifact saved to the S3 after PR tarantool/tarantool#8476 if the link exists. This link will be stored in the `multivac-table` bucket.
Resolves #95
> gather_data: add the link to the artifact archive

- multivac/gather_data.py
Logs from FreeBSD runners can provde en error:
```
Traceback (most recent call last):
File "./multivac/gather_data.py", line 612, in <module>
result.gather_data()
File "./multivac/gather_data.py", line 317, in gather_data
job_failure_type, failure_line = detect_error(logs,
File "./multivac/gather_data.py", line 95, in detect_error
for number, line in enumerate(reverse_readline(logs)):
File "./multivac/gather_data.py", line 73, in reverse_readline
lines = buffer.split('\n')
UnboundLocalError: local variable 'buffer' referenced before assignment
```
We get this error when we have UnicodeDecodeError on reading line.
This patch fixes this error handling.
> fix reverse readline

- .github/workflows/main.yml
Multivac dashboard collects all the info we have in the CSV collected
with `last_seen`, so we don't need to duplicate this feature.
> ci: stop making CSV 

- .github/workflows/main.yml
On the 2nd of July LTS branch in tarantool/tarantool was renamed to release/2.11, so we need to rename this in the CI.
> ci: rename LTS branch

- multivac/gather_data.py
To calculate job duration, we use the function called previously `get_time_in_queue`, so it was renamed. Added new tag to InfluxDB and new point to JSON.
Resolves #131
> gather_data: collect data about job duration
